[package]
name = "redis-glue"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.17.0", features = ["tokio-comp","aio", "cluster"] }
actix-rt = "1"
