[package]
name = "redis-glue"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.20.2", features = ["tokio-comp","aio", "cluster"] }

[dev-dependencies]
actix-rt = "2"
